using UnityEditor;
using UnityEngine;
using UnityEngine.UIElements;

[CustomEditor(typeof(AudioData))]
public class AudioDataPropertyDrawer : Editor
{
    [SerializeField] private VisualTreeAsset audioDataPropertyDrawerTemplate = null;
    [SerializeField] private TextAsset SFXPlayerMethodFile = null;

    private AudioData currentData = null;

    #region VisualElement names
    private readonly string createSFXButtonName = "CreateSFXPlayerMethodsButton";

    #endregion

    public override VisualElement CreateInspectorGUI()
    {
        if (audioDataPropertyDrawerTemplate == null)
        {
            Debug.LogError("AudioDataPropertyDrawer: VisualTreeAsset reference is missing. Please assign it in the inspector.");
            return base.CreateInspectorGUI();
        }

        currentData = (AudioData)target;

        var root = audioDataPropertyDrawerTemplate.CloneTree();

        var createSFXButton = root.Q<Button>(createSFXButtonName);
        createSFXButton?.RegisterCallback<ClickEvent>(evt => CreateSFXPlayerMethods());

        return root;
    }

    public void CreateSFXPlayerMethods()
    {
        if (currentData == null || SFXPlayerMethodFile == null)
        {
            Debug.LogError("AudioDataPropertyDrawer: Missing reference to AudioData or SFXPlayerMethodFile. Please ensure both are assigned.");
            return;
        }

        string content = "";

        foreach (var soundBank in currentData.SoundBanks)
        {
            // public void PlayButtonClickSound() => PlaySound("ButtonClick");

            string trimmedName = soundBank.Name.Replace(" ", "");
            string methodName = $"\tpublic void Play{trimmedName}Sound() => PlaySound(\"{trimmedName}\");";
            content += $"{methodName}\n";
        }

        string fileContent = 
$@"//// This file is auto-generated by AudioDataPropertyDrawer. ////
using UnityEngine;

public partial class AudioManager : MonoBehaviour
{{
{content}
}}";

        string filePath = AssetDatabase.GetAssetPath(SFXPlayerMethodFile);

        System.IO.File.WriteAllText(filePath, fileContent);
        AssetDatabase.Refresh();

        Debug.Log("AudioDataPropertyDrawer: SFX player methods generated successfully.");
    }
}
