//// This file is auto-generated by AudioDataPropertyDrawer. ////
using UnityEngine;

public partial class AudioManager : MonoBehaviour
{
    public void PlayButtonClickSound() => PlaySound("ButtonClick");
public void PlayUUUSound() => PlaySound("UUU");

}